sudo apt remove -y gnome-mines;
sudo apt remove -y gnome-mahjongg;
sudo apt remove -y aisleriot;
sudo apt remove -y gnome-calendar;
sudo apt remove -y remmina;
sudo apt remove -y gnome-calculator;
sudo apt remove -y rhythmbox;
sudo apt remove -y gnome-sudoku;
sudo apt remove -y thunderbird;
sudo apt remove -y firefox;
sudo apt remove -y gnome-todo;
sudo apt remove -y transmission-gtk;
sudo apt autoremove;
